name: Chocolatine

on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'

env:
  MIRROR_URL: "git@github.com:EpitechPromo2027/B-DOP-200-NAN-2-1-chocolatine-florian.gaudin.git"
  EXECUTABLE: "binary"

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/epitech/coding-style-checker:latest"
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Check coding style
        run: check.sh $(pwd) $(pwd)
  push_to_mirror:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Push to mirror
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
